---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-from-ns-acancell-learning-2
spec:
  podSelector:
    matchLabels:
      deployment: acancell-goping
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: acancell-learning-2
    ports: []
#    - port: 8080
#      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acancell-goping
spec:
  rules:
  - host: acancell-goping.example.internal
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: acancell-goping
            port:
              name: http
#---
#apiVersion: route.openshift.io/v1
#kind: Route
#metadata:
#  name: acancell-goping
#spec:
#  host: acancell-goping.example.internal
#  to:
#    kind: Service
#    name: acancell-goping
#  port:
#    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: acancell-goping
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: acancell-goping
    env: dev
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acancell-goping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acancell-goping
  template:
    metadata:
      labels:
        app: acancell-goping
        env: dev
    spec:
      containers:
      - name: acancell-goping
        image: quay.io/acancell-redhat-training/goping:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080		
          initialDelaySeconds: 3
          periodSeconds: 2
